export default {
    categoryChartData: {
        type: 'serial',
        pathToImages: 'https://www.amcharts.com/lib/3/images/',
        categoryField: 'date',
        dataDateFormat: 'YYYY-MM-DD',
        colors: ['#C1C1C1', '#00C535', '#C91F37'],
        color: '#1B1B1E',
        fontFamily: 'Proxima Nova',
        fontSize: 14,
        categoryAxis: {
            parseDates: true,
            gridAlpha: 1,
            gridColor: '#F2F2F6',
            title: '',
        },
        chartCursor: {
            enabled: true,
            bulletSize: 6,
            cursorColor: '#662D91',
        },
        chartScrollbar: {
            enabled: true,
            backgroundColor: '#E8E8EF',
            graphFillColor: '#D7D7E2',
            graphLineColor: '#d7d7e2',
            selectedBackgroundColor: '#F2F2F6',
            tabIndex: 0,
        },
        trendLines: [],
        graphs: [
            {
                accessibleLabel: '[[category]]: [[value]]',
                balloonText: 'Onboard on [[category]]: <b>[[value]]</b>',
                bullet: 'none',
                fillAlphas: 0.3,
                id: 'AmGraph-1',
                lineThickness: 0,
                title: 'graph 1',
                valueField: 'column-1',
                type: 'column',
            },
            {
                accessibleLabel: '[[category]]: [[value]]',
                balloonText: 'Approved on [[category]]: <b>[[value]]</b>',
                bullet: 'round',
                id: 'AmGraph-2',
                lineThickness: 2,
                title: 'graph 2',
                valueField: 'column-2',
                type: 'smoothedLine',
            },
            {
                accessibleLabel: '[[category]]: [[value]]',
                balloonText: 'Rejected on [[category]]: <b>[[value]]</b>',
                bullet: 'round',
                id: 'AmGraph-3',
                lineThickness: 2,
                title: 'graph 3',
                valueField: 'column-3',
                type: 'smoothedLine',
            },
        ],
        guides: [],
        valueAxes: [
            {
                id: 'ValueAxis-1',
                gridAlpha: 1,
                gridColor: '#F2F2F6',
                title: 'Total Activities',
            },
        ],
        allLabels: [],
        balloon: {
            fillAlpha: 1,
        },
        titles: [],
        dataProvider: [
            {
                date: '2019-06-01',
                'column-1': 8,
                'column-2': '6',
                'column-3': '2',
            },
            {
                date: '2019-06-02',
                'column-1': 6,
                'column-2': '3',
                'column-3': '3',
            },
            {
                date: '2019-06-03',
                'column-1': '12',
                'column-2': '7',
                'column-3': '5',
            },
            {
                date: '2019-06-04',
                'column-1': '14',
                'column-2': '6',
                'column-3': '8',
            },
            {
                date: '2019-06-05',
                'column-1': '19',
                'column-2': '11',
                'column-3': '8',
            },
            {
                date: '2019-06-06',
                'column-1': '13',
                'column-2': '6',
                'column-3': '7',
            },
            {
                date: '2019-06-07',
                'column-1': '16',
                'column-2': '8',
                'column-3': '8',
            },
            {
                date: '2019-06-08',
                'column-1': '19',
                'column-2': '11',
                'column-3': '8',
            },
            {
                date: '2019-06-09',
                'column-1': '13',
                'column-2': '6',
                'column-3': '7',
            },
            {
                date: '2019-06-10',
                'column-1': '16',
                'column-2': '8',
                'column-3': '8',
            },
            {
                date: '2019-06-11',
                'column-1': 18,
                'column-2': '16',
                'column-3': '2',
            },
            {
                date: '2019-06-12',
                'column-1': 16,
                'column-2': '6',
                'column-3': '10',
            },
            {
                date: '2019-06-13',
                'column-1': '12',
                'column-2': '7',
                'column-3': '6',
            },
            {
                date: '2019-06-14',
                'column-1': '18',
                'column-2': '9',
                'column-3': '9',
            },
            {
                date: '2019-06-15',
                'column-1': '14',
                'column-2': '11',
                'column-3': '3',
            },
            {
                date: '2019-06-16',
                'column-1': '13',
                'column-2': '4',
                'column-3': '9',
            },
            {
                date: '2019-06-17',
                'column-1': '16',
                'column-2': '9',
                'column-3': '7',
            },
            {
                date: '2019-06-18',
                'column-1': '20',
                'column-2': '8',
                'column-3': '12',
            },
            {
                date: '2019-06-19',
                'column-1': '14',
                'column-2': '4',
                'column-3': '10',
            },
            {
                date: '2019-06-20',
                'column-1': '13',
                'column-2': '5',
                'column-3': '8',
            },
            {
                date: '2019-06-21',
                'column-1': 18,
                'column-2': '8',
                'column-3': '10',
            },
            {
                date: '2019-06-22',
                'column-1': 6,
                'column-2': '3',
                'column-3': '3',
            },
            {
                date: '2019-06-23',
                'column-1': '12',
                'column-2': '7',
                'column-3': '5',
            },
            {
                date: '2019-06-24',
                'column-1': '14',
                'column-2': '6',
                'column-3': '8',
            },
            {
                date: '2019-06-25',
                'column-1': '14',
                'column-2': '11',
                'column-3': '3',
            },
            {
                date: '2019-06-26',
                'column-1': '19',
                'column-2': '8',
                'column-3': '11',
            },
            {
                date: '2019-06-27',
                'column-1': '16',
                'column-2': '9',
                'column-3': '7',
            },
            {
                date: '2019-06-28',
                'column-1': '19',
                'column-2': '6',
                'column-3': '13',
            },
            {
                date: '2019-06-29',
                'column-1': '20',
                'column-2': '6',
                'column-3': '14',
            },
            {
                date: '2019-06-30',
                'column-1': '14',
                'column-2': '5',
                'column-3': '9',
            },
        ],
    },
}
